package com.fineframework.persistence.dao;

import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;

import com.fineframework.persistence.domain.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated Thu May 17 13:11:22 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated Thu May 17 13:11:22 CST 2018
	 */
	@CacheEvict(allEntries = true,value="test")
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated Thu May 17 13:11:22 CST 2018
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated Thu May 17 13:11:22 CST 2018
	 */
	@Cacheable(value = "test", keyGenerator = "keyGenerator")
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated Thu May 17 13:11:22 CST 2018
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user
	 *
	 * @mbggenerated Thu May 17 13:11:22 CST 2018
	 */
	int updateByPrimaryKey(User record);
}